--Show last name, salary, job title, city and country
--for employees led by King directly

--Solution:
SELECT LAST_NAME, SALARY, JOB_TITLE, CITY, COUNTRY_ID
FROM (
    SELECT * FROM EMPLOYEES
    WHERE MANAGER_ID=100
    )
E
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_ID
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
LEFT JOIN LOCATIONS L ON D.LOCATION_ID = L.LOCATION_ID