--Show all departments with their employees
--Also show departments without (2 solutions)

--Solution1
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E
RIGHT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME

--Solution2
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E
ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_NAME